/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.ucbootcamp.group1inventorysystem;

/**
 *
 * @author yeems214
 */
public class aboutus extends javax.swing.JFrame {

    /**
     * Creates new form aboutUS
     */
    public aboutUS() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        madewithlove = new javax.swing.JLabel();
        salimbot = new javax.swing.JLabel();
        inso = new javax.swing.JLabel();
        abarca = new javax.swing.JLabel();
        AboutUs = new javax.swing.JLabel();
        foreground = new javax.swing.JLabel();
        background = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jButton1.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        jButton1.setText("Back");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(150, 493, 110, 40);

        madewithlove.setFont(new java.awt.Font("Segoe UI Semibold", 0, 12)); // NOI18N
        madewithlove.setText("Made with <3 from the UC Banilad BSIT-SE Class.");
        getContentPane().add(madewithlove);
        madewithlove.setBounds(350, 500, 270, 30);

        salimbot.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        salimbot.setText("Dimple Lavigne Salimbot");
        getContentPane().add(salimbot);
        salimbot.setBounds(620, 390, 220, 30);

        inso.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        inso.setText("John Paul Inso");
        getContentPane().add(inso);
        inso.setBounds(430, 390, 120, 30);

        abarca.setFont(new java.awt.Font("Segoe UI Semibold", 0, 18)); // NOI18N
        abarca.setText("Francis Roel L. Abarca");
        getContentPane().add(abarca);
        abarca.setBounds(180, 390, 180, 30);

        AboutUs.setFont(new java.awt.Font("Segoe UI Semibold", 0, 36)); // NOI18N
        AboutUs.setText("About the Team");
        getContentPane().add(AboutUs);
        AboutUs.setBounds(360, 50, 270, 40);

        foreground.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ucbootcamp/group1inventorysystem/blur.jpg"))); // NOI18N
        foreground.setText("jLabel2");
        getContentPane().add(foreground);
        foreground.setBounds(130, 40, 730, 510);

        background.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/ucbootcamp/group1inventorysystem/lowpoly1.jpg"))); // NOI18N
        background.setText("jLabel1");
        getContentPane().add(background);
        background.setBounds(0, 0, 990, 610);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
       LoginPage f2= new LoginPage();
       f2.setVisible(true);// TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(aboutUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(aboutUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(aboutUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(aboutUS.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new aboutUS().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel AboutUs;
    private javax.swing.JLabel abarca;
    private javax.swing.JLabel background;
    private javax.swing.JLabel foreground;
    private javax.swing.JLabel inso;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel madewithlove;
    private javax.swing.JLabel salimbot;
    // End of variables declaration//GEN-END:variables
}
